name: auto-build

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: ["from_dvc_packages"]
  
jobs:
  Updating_dist:
    runs-on: ubuntu-latest
    concurrency: build_dists
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set git cred
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          with:
            token: '${{ secrets.GH_TOKEN }}'

      - name: updating and signing releases file
        env:
            SEC_PASS: ${{ secrets.SEC_PASS }}
            SEC_KEY: ${{ secrets.SEC_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            echo "Jai ho"
            bash ./scripts/trigger.sh
